@startuml

package "Adapter Pattern"{
    abstract class APlayer{
        +attack():void
        +defense():void
    }
    class QiaoDan extends APlayer
    class KeBi extends APlayer
    class TranslaterAdapter extends APlayer
    class TranslaterAdapter
    note top:将一个接口转换为客户所需要的另外一个接口\n使原来由于接口不兼容而不能在一起工作的两\n个类能够在一起正常工作
    TranslaterAdapter --> YaoMing
    class YaoMing
}

@enduml