@startuml
interface IVistor{
    void vistorMan(Man manager);
    void vistorWoman(Woman expler);
}
note left:访问者协议

class SuccVistor
note left:成功的访问者
class SuccVistor implements IVistor

class FailVistor
note right:失败的访问者
class FailVistor implements IVistor

class Person{
    String name;
    void accept(IVistor vistor);
}
note left:被访问的实体对象

class Man extends Person{
}
class Woman extends Person{
}
Person -.> IVistor

@enduml