@startuml
skinparam classAttributeIconSize 0

package "class Singleton(单例模式)" #DDDDDD {

    class Singleton{
    -Singleton()
    +getInstance():Singleton
    }
    note right: 单例类

    'Clent ..>Singleton
    Singleton <.. Client
}

@enduml