@startuml
skinparam classAttributeIconSize 0
package Prototype{
    abstract class APerson
    class PrototypePerson
    note bottom:由原型对象来指定创建对象的类型，\n并通过拷贝原型对象来新创建的对象
    class PrototypePerson extends APerson{
        +clonePerson():APerson
    }
    class CopyPerson
    note bottom:新建对象
    class CopyPerson extends APerson
    PrototypePerson .> CopyPerson
}

@enduml