@startuml
package "Chain Pattern"{
    abstract class Employee {
        #mEmployee:Employee
        +Employee(Employee employee)
        +request(int day):void
    }
    note top:当前对象持有下家对象的引用而形成一个链条，请求在这个链条上传递\n直到有对象能够处理该对象的请求为止
    class SmallLeader extends Employee
    class MiddleLeader extends Employee
    class BigLeader extends Employee

    SmallLeader->MiddleLeader
    MiddleLeader->BigLeader
}
@enduml